variable "common_vars" {}
variable "acm" {}
variable "ecs_role" {}
variable "vpc" {}
variable "sg" {}
variable "rds" {}
variable "elasticache" {}
variable "bastion" {}
variable "alb" {}
variable "s3-cf" {}